name: Publish Docker image

on:
  push:
    tags:
      - 'v*'
env:
  VERSION:  ${{ github.ref_name }}
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Get tag name
        id: extract_tag
        run: echo "Tag name is ${{ github.ref }}"
        shell: bash
      
      - name: SemVer Tag
        id: extract_semver
        run: |
          if [[ "${{ github.ref }}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+ ]]; then
            echo "{SEMVER_TAG}={BASH_REMATCH[0]}" >> $GITHUB_ENV
          else
            echo "No SemVer tag found."
          fi
        shell: bash
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            baykara/sample-app
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: VERSION=${{ env.VERSION }}
      - name: Create and publish helm package 
        run: | 
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          helm package ./sample-app
          echo ${{ secrets.CI_TOKEN }} | helm registry login ghcr.io -u mbaykara --password-stdin
          helm push *.tgz oci://ghcr.io/mbaykara/